twig:
    globals:  { 
        app_name: 'Opportunities at Timar ', 
        app_description: 'Timar Ethiopia ', 
        organization: timar,  
        app_url: "https://opportunity.timar.et",
        app_email: opportunity@timar.et,
        site_logo: timar.png, 
        copyright: 'timar-opportunity', 
        navbar_background: dark, 
        acronym: 'timar-opportunity',
        signatures: 'uploads/signatures/' ,
        corporate_color: '#54b4', 
        profile_pictures: 'uploads/files/profile_pictures',
        motto: 'Motto',  
        site_setting: '%kernel.project_dir%/uploads/files/site_setting/',
        contact_us: 'timar-opportunity', 
        about: 'timar-opportunity',
        privacy_statement: 'timar-opportunity' 
        }
