twig:
    globals:  { 
        app_name: 'EPHI-IRB', 
        app_description: 'Institutional Review Board System', 
        organization: EPHI, 
        # app_url: '', 
        # app_url: sero.ephi.gov.et, 
        app_url: "http://irb.ephi.gov.et",
        app_email: irb@ephi.gov.et,
        site_logo: ephi.png, 
        copyright: 'EPHI-IRB', 
        navbar_background: dark, 
        acronym: 'EPHI-IRB',
        signatures: 'uploads/signatures/' ,
        corporate_color: '#54b4', 
        profile_pictures: 'uploads/files/profile_pictures',
        motto: 'Motto',  
        site_setting: '%kernel.project_dir%/uploads/files/site_setting/',
        contact_us: 'EPHI-IRB', 
        about: 'EPHI-IRB',
        privacy_statement: 'EPHI-IRB' 
        }
