twig:
    file_name_pattern: '*.twig'
    form_themes:
        ['bootstrap_5_layout.html.twig',]
    globals:
        my_global_variable: 'Your Value Here'
when@test:
    twig:
        strict_variables: true
